"""Stable, dependency-free public facade for Portable Memory Engine."""

from portable_memory_engine.adapters import (
    DeterministicEmbedder,
    FixedClock,
    InMemoryMemoryStore,
    ScriptedChatModel,
)
from portable_memory_engine.application import (
    AddMemoryCommand,
    AddMemoryResult,
    AddResultStatus,
    RecallMode,
    RecallRequest,
    RecallResult,
)
from portable_memory_engine.domain import (
    AccessDeniedError,
    CapabilityError,
    ConflictError,
    ConversationMessage,
    DeleteCommand,
    DeleteMemoryCommand,
    DeleteResult,
    DeleteScopeCommand,
    DeleteSessionCommand,
    DeleteSubjectCommand,
    DomainValidationError,
    Embedding,
    EmbeddingTask,
    IdempotencyConflictError,
    LifecycleError,
    MemoryEngineError,
    MemoryKind,
    MemoryMatch,
    MemoryPage,
    MemoryQuery,
    MemoryRecord,
    MemoryScope,
    MemorySubject,
    PromptResolutionError,
    ProviderError,
    ProviderParseError,
    ProviderUnavailableError,
    StaleEventError,
    StoreError,
    StoreUnavailableError,
)
from portable_memory_engine.facade import MemoryEngine
from portable_memory_engine.ports import (
    ChatModel,
    ChatRequest,
    ChatResponse,
    Embedder,
    EmbeddingRequest,
    MemoryStore,
    PromptProvider,
    PromptRequest,
    PromptTemplate,
)
from portable_memory_engine.prompts import DefaultPromptProvider

__version__ = "0.1.0.dev0"

__all__ = (
    "AccessDeniedError",
    "AddMemoryCommand",
    "AddMemoryResult",
    "AddResultStatus",
    "CapabilityError",
    "ChatModel",
    "ChatRequest",
    "ChatResponse",
    "ConflictError",
    "ConversationMessage",
    "DefaultPromptProvider",
    "DeleteCommand",
    "DeleteMemoryCommand",
    "DeleteResult",
    "DeleteScopeCommand",
    "DeleteSessionCommand",
    "DeleteSubjectCommand",
    "DeterministicEmbedder",
    "DomainValidationError",
    "Embedder",
    "Embedding",
    "EmbeddingRequest",
    "EmbeddingTask",
    "FixedClock",
    "IdempotencyConflictError",
    "InMemoryMemoryStore",
    "LifecycleError",
    "MemoryEngine",
    "MemoryEngineError",
    "MemoryKind",
    "MemoryMatch",
    "MemoryPage",
    "MemoryQuery",
    "MemoryRecord",
    "MemoryScope",
    "MemoryStore",
    "MemorySubject",
    "PromptProvider",
    "PromptRequest",
    "PromptResolutionError",
    "PromptTemplate",
    "ProviderError",
    "ProviderParseError",
    "ProviderUnavailableError",
    "RecallMode",
    "RecallRequest",
    "RecallResult",
    "ScriptedChatModel",
    "StaleEventError",
    "StoreError",
    "StoreUnavailableError",
    "__version__",
)
